baseurl: /
languageCode: zh-cn
title: 田野梦呓
theme: hugo-ivy
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "主页"
      url: "/"
      weight: 1
    - name: "随心记"
      url: "/heart/"
      weight: 4
    - name: "关于"
      url: "/about/"
      weight: 2
    - name: "类别"
      url: "/categories/"
      weight: 3
    - name: "标签"
      url: "/tags/"
      weight: 4
#    - name: "订阅"
#      url: "/index.xml"

params:
  description: "A Hugo theme ported from the static site generator Ivy."
  footer: "&copy; [Yihui Xie](https://yihui.org) 2017-{Year} | [Github](https://github.com/yihui)"
  highlightjsLang: ["latex"]
  highlightjsTheme: "github"
  highlightjsVersion: "11.7.0"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
